bookSystem/lib/bookSystem_web/router.ex
defmodule BookSystemWeb.Router do
  use BookSystemWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookSystemWeb do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/user/loans", UserController, :loans
    get "/user/extendLoad", UserController, :extend
  end
end

bookSystem/lib/bookSystem/account/user.ex
defmodule BookSystem.Account.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :name, :string
    field :password, :string
    field :username, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:name, :username, :password])
    |> validate_required([:name, :username, :password])
  end
end

bookSystem/lib/bookSystem/application.ex
defmodule BookSystem.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(BookSystem.Repo, []),
      # Start the endpoint when the application starts
      supervisor(BookSystemWeb.Endpoint, []),
      # Start your own worker by calling: BookSystem.Worker.start_link(arg1, arg2, arg3)
      # worker(BookSystem.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: BookSystem.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    BookSystemWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

bookSystem/lib/bookSystem/book/catalogs.ex
defmodule BookSystem.Book.Catalogs do
  use Ecto.Schema
  import Ecto.Changeset

  @unique_constraint {:title, :string, autogenerate: false}
  schema "catalogs" do
    field :code, :string
    field :title, :string
    has_one :loans, BookSystem.Book.Loans, foreign_key: :title
    timestamps()
  end

  @doc false
  def changeset(catalog, attrs) do
    catalog
    |> cast(attrs, [:title, :code])
    |> validate_required([:title, :code])
    |> unique_constraint(:title)
  end
end

bookSystem/lib/bookSystem/book/loans.ex
defmodule BookSystem.Book.Loans do
  use Ecto.Schema
  import Ecto.Changeset


  schema "loans" do
    field :code, :string
    field :end_date, :string
    field :start_date, :string
    field :times_extended, :string
    belongs_to :catalogs, BookSystem.Book.Catalogs, foreign_key: :title, references: :title, type: :string

    timestamps()
  end

  @doc false
  def changeset(loans, attrs) do
    loans
    |> cast(attrs, [:title, :code, :start_date, :end_date, :times_extended])
    |> validate_required([:title, :code, :start_date, :end_date, :times_extended])  
    |> foreign_key_constraint(:title)
  end
end

bookSystem/lib/bookSystem/repo.ex
defmodule BookSystem.Repo do
  use Ecto.Repo, otp_app: :bookSystem

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

bookSystem/lib/bookSystem_web/controllers/page_controller.ex
defmodule BookSystemWeb.PageController do
  use BookSystemWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

bookSystem/lib/bookSystem_web/controllers/user_controller.ex
defmodule BookSystemWeb.UserController do
    use BookSystemWeb, :controller
    alias BookSystem.Book.Loans
    alias BookSystem.Repo
    import Ecto.Query, only: [from: 2]
  
    def loans(conn, _params) do
        query = from l in Loans,
                select: {l.title, l.code, l.start_date, l.end_date, l.times_extended}
        conn
        |> put_flash(:info, "Your loans")
        |> render "loans.html", tuples: Repo.all(query)
    end

    def extend(conn, _params) do
        query = from l in Loans,
                select: {l.title, l.code, l.start_date, l.end_date, l.times_extended}
        conn
        |> put_flash(:info, "extended")
        |> render "loans.html", tuples: Repo.all(query)
    end
  end
  

bookSystem/lib/bookSystem_web/views/error_view.ex
defmodule BookSystemWeb.ErrorView do
  use BookSystemWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

bookSystem/lib/bookSystem_web/views/layout_view.ex
defmodule BookSystemWeb.LayoutView do
  use BookSystemWeb, :view
end

bookSystem/lib/bookSystem_web/views/page_view.ex
defmodule BookSystemWeb.PageView do
  use BookSystemWeb, :view
end

bookSystem/lib/bookSystem_web/views/user_view.ex
defmodule BookSystemWeb.UserView do
    use BookSystemWeb, :view
  end
  

bookSystem/lib/bookSystem_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello BookSystem!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

bookSystem/lib/bookSystem_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

bookSystem/lib/bookSystem_web/templates/user/extendLoad.html.eex
<h2>List of free parking lots</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Times extended</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<%= for t <- @tuples do %>
    <tr>
      <td><%= elem(t, 0) %></td>
      <td><%= elem(t, 1) %></td>
      <td><%= elem(t, 2) %></td>
      <td><%= elem(t, 3) %></td>
      <td><%= elem(t, 4) %></td>
      <td><%= link "Extend", to: user_path(@conn, :extend, @tuples) %></td>
      
    </tr>
<% end %>
  </tbody>
</table>

bookSystem/lib/bookSystem_web/templates/user/loans.html.eex
<h2>List of free parking lots</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Code</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Times extended</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<%= for t <- @tuples do %>
    <tr>
      <td><%= elem(t, 0) %></td>
      <td><%= elem(t, 1) %></td>
      <td><%= elem(t, 2) %></td>
      <td><%= elem(t, 3) %></td>
      <td><%= elem(t, 4) %></td>
      <td id = "link"><%= link "Extend", to: user_path(@conn, :extend, @t) %></td>
      
    </tr>
<% end %>
  </tbody>
</table>